version: "3.8"

services:
  mcserver:
    build: .
    container_name: forge-server
    ports:
      - "25565:25565"
    volumes:
      - ./world:/server/world
      - ./mods:/server/mods
      - ./config:/server/config
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 12g